### ISSUE TITLE
Root Certificatates release date frequency?

### ISSUE THREAD

**Issue by Pocokk** [JohnTHaller/RootCertificateUpdatesForLegacyWindows#1]
Dear JohnTHaller,

As I can see, prior to the last update was a year ago in 2022-July. Is this mean the *future* update can be expected in another year's time, in mid 2024? 

Thank you for your answer, best regards,
Pocok

**Comment by JohnTHaller** [comment]
I'm going to update it quarterly. The certs don't update that often, but I think it will help people feel better about it.

**Comment by Pocokk** [comment]
Appreciate your quick reply!
