### ISSUE TITLE
how to convert sst root certificates to pem?

### ISSUE THREAD

**Issue by hhihhio** [JohnTHaller/RootCertificateUpdatesForLegacyWindows#2]
I want to install these root certificates on android so I need pem root certificates

**Comment by JohnTHaller** [comment]
I don't think there's an easy way to convert SST to PEM without importing and exporting within Windows. I could add PEM to the next release in a week or so if that works for you.

**Comment by JohnTHaller** [comment]
I've added PFX files for both root and intermediate. They have a password of 12345 and should work in Android.
