### ISSUE TITLE
Accidentally loaded Intermediate into Root. Can it be fixed?

### ISSUE THREAD

**Issue by Link98745** [JohnTHaller/RootCertificateUpdatesForLegacyWindows#3]
Accidentally put the windows intermediate thing into the trusted root. AFter i realized I installed the correct one into it. Does it over write it? Can i fix it?

**Comment by Link98745** [comment]
please i really don't want to reinstall windows xp again

**Comment by JohnTHaller** [comment]
![Intermediate Certificates](https://github.com/JohnTHaller/RootCertificateUpdatesForLegacyWindows/assets/8020860/b7f4a4e7-7e34-43d5-8b4c-cee8902d1a36)
Here is the list of the certificates included in the current WindowsIntermediate.sst that you can manually remove from root.
