### ISSUE TITLE
What should we do with the original WinXP .sst files?

### ISSUE THREAD

**Issue by LuxLOL** [JohnTHaller/RootCertificateUpdatesForLegacyWindows#4]
Should the new .sst files be placed next to the original Windows XP .sst files in a Package Installer or should we replace the "roots.sst" with the "WindowsRoot.sst" file and the "updroots.sst" with the "WindowsIntermediate.ss" file?
https://msfn.org/board/topic/175170-root-certificates-and-revoked-certificates-for-windows-xp

**Comment by JohnTHaller** [comment]
Once you've imported the certificates, Windows doesn't need the files anymore. So you can delete the old ones. And the new ones after importing if you'd like.

**Comment by LuxLOL** [comment]
Do you know a command code to install this with a Batch file?
I tried this below but I get a ASN 267 error.

".\certutil.exe" -addstore "Root" ".\WindowsRoot.sst"
".\certutil.exe" -addstore "CA" ".\WindowsIntermediate.sst"
